# Generated by Django 3.2.13 on 2022-09-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20220712_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='goal_coins_per_day',
            field=models.IntegerField(default=1000),
        ),
    ]
